template = ""
rev_id = 9
template_sha = "40afa223ab00844a035cff537a1d85d88c975bf8"

[replacements]
__LICENSE__ = "CC-BY-4.0"
__UND2C_SRC__ = "vro"
__UND2C_TRG__ = "et"
__UNDEFINED_SOURCE__ = "Võro"
__UNDEFINED_TARGET__ = "Estonian"
__UND_SRC__ = "vro"
__UND_TRG__ = "est"
