template = ""
rev_id = 5
template_sha = "b1bcc12f5675c5b86f53da0a290c53417f28d6e3"

[replacements]
__LICENSE__ = "CC-BY-4.0"
__UND2C_SRC__ = "vro"
__UND2C_TRG__ = "et"
__UNDEFINED_SOURCE__ = "Võro"
__UNDEFINED_TARGET__ = "Estonian"
__UND_SRC__ = "vro"
__UND_TRG__ = "est"
