template = ""
rev_id = 7
template_sha = "94893e7a5cd0adce3abaa3e278710450dd114995"

[replacements]
__LICENSE__ = "CC-BY-4.0"
__UND2C_SRC__ = "vro"
__UND2C_TRG__ = "et"
__UNDEFINED_SOURCE__ = "Võro"
__UNDEFINED_TARGET__ = "Estonian"
__UND_SRC__ = "vro"
__UND_TRG__ = "est"
