theme: jekyll-theme-giellalt
title: Dictionary for Võro ⇒ Estonian
description: An electronic dictionary from Võro to Estonian

defaults:
  - scope: { path: "" }
    values:
      layout: default

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
